[package]
name = "pknocker"
version = "0.1.0"
edition = "2021"

[profile.release]
lto = true
strip = true

[dependencies]
anyhow = "1.0.70"
clap = { version = "4.2.4", features = ["derive"] }
env_logger = "0.10.0"
log = "0.4.17"
